[tool.poetry]
name = "pytibia"
version = "0.1.0"
description = ""
authors = ["lucasmonstro <joao.galiano.silva@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.12,<3.12"
xxhash = "^3.0.0"
Rx = "^3.2.0"
PyAutoGUI = "^0.9.53"
Pillow = "^9.1.1"
opencv-python = "^4.6.0.66"
numpy = "^1.21.0"
nptyping = "^2.2.0"
ahocorapy = "^1.6.1"
dxcam = {git = "https://github.com/ra1nty/DXcam.git"}
scipy = "^1.9.1"
pyee = "^9.0.4"


[tool.poetry.group.test.dependencies]
pytest = "^7.1.3"
pytest-mock = "^3.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
